version: '3.8'

services:
  avito-app:
    build: ./
    ports:
      - 8081:8081
    depends_on:
      - db
    environment:
      - DB_PASSWORD=task

  db:
    container_name: "db"
    restart: always
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_PASSWORD = ${DB_PASSWORD}
      - POSTGRES_USER = ${DB_USER}
      - POSTGRES_DB = ${DB_NAME}
    ports:
      - "5436:5432"
    expose: 
      - "5432"
